name: Go mod auto updater
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.18.8
      - name: Updating go mod
        run: |
          go mod tidy
          go get -u
          go mod download
      - name: Git push 
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "CI: Auto update go mod at $(date +"%m-%d %H:%M")"
          git push